### ISSUE TITLE
Deployment: Deploy the Develop Branch on Heroku 

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/web-dev-rooms#144]
Make sure that we can deploy the Develop Branch on Heroku https://develop-web-dev-rooms.herokuapp.com/

![image](https://user-images.githubusercontent.com/6642037/101366876-cb823700-38a5-11eb-9873-384a50c5eb4b.png)

Check the env variables on https://dashboard.heroku.com/apps/develop-web-dev-rooms/settings and DO NOT SHARE or COMMIT any information about Users or Passwords.

**Comment by AnilMula** [comment]
deployed successfully with put any PR


and running at [here](https://develop-web-dev-rooms.herokuapp.com/)
