### ISSUE TITLE
DB: Create a migration and initial seed for the Groups table

### ISSUE THREAD

**Issue by tpetrina** [HackYourFuture-CPH/web-dev-rooms#22]
Create a Knex migration for the Groups table. Also, consider adding a seed file for development to add a couple of initial groups.
<img width="249" alt="image" src="https://user-images.githubusercontent.com/1407815/99183249-a84ae880-273a-11eb-8075-7b77baa81dc6.png">

**Comment by dpfernandes** [comment]
The task will handle on this issue #65
