### ISSUE TITLE
DB: Create a migration and initial seed for the Topics table

### ISSUE THREAD

**Issue by tpetrina** [HackYourFuture-CPH/web-dev-rooms#23]
Create a Knex migration for the Topics table. Also, consider adding a seed file for development to add a couple of initial topics.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/1407815/99183234-96694580-273a-11eb-836c-dcaee32a0247.png">

**Comment by dpfernandes** [comment]
This task will be handle on issue #63
