### ISSUE TITLE
DB: Create a migration and initial seed for the Companies table

### ISSUE THREAD

**Issue by tpetrina** [HackYourFuture-CPH/web-dev-rooms#25]
Create a Knex migration for the Companies table. Also, consider adding a seed file for development to add a couple of initial companies.

> Note: Consider what data is needed for a company.

Some company data can be seen here:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/1407815/99183330-2f985c00-273b-11eb-9b7a-c4de6f8710ae.png">

**Comment by claudion3** [comment]
Hello, do we have DB Model Diagram?

**Comment by dpfernandes** [comment]
This task will be handled on issue #65 and #66
