### ISSUE TITLE
Admin should be able to delete an event

### ISSUE THREAD

**Issue by tpetrina** [HackYourFuture-CPH/web-dev-rooms#301]
<img width="253" alt="image" src="https://user-images.githubusercontent.com/1407815/105070229-42a11280-5a83-11eb-9029-ee914c9af0d1.png">

Display a modal when the user clicks the cancel button on the list of events. Check if that modal already exist and adapt it if necessary.

The DELETE endpoint should be changed from `'/:userId/:eventId'` to `/:eventId` and it should pass the `userId` from `req`.
Add validation to the function to check if the user is an admin and return 403 if they aren't.

**Comment by AnilMula** [comment]
this issue addressed by PR https://github.com/HackYourFuture-CPH/web-dev-rooms/pull/304
