### ISSUE TITLE
Databases: Create Migrations for Events, Event_users, Event_students, Event_mentors and Questions

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/web-dev-rooms#64]
Create the Knex Migrations in order to create the DB schema for the following tables:

Events, Event_users, Event_students, Event_mentors and Questions  - Topic Blue

<img width="727" alt="Screenshot 2020-11-22 at 15 21 34" src="https://user-images.githubusercontent.com/6642037/99906354-efa31d00-2cd6-11eb-87f7-c998971e2dfd.png">

Please consider the DB Diagram - https://dbdiagram.io/d/5fb801913a78976d7b7cc7d8

**Comment by claudion3** [comment]
Yuuupi, this will be fun
